# src/schemas.py

from pydantic import BaseModel, Field, ConfigDict, field_validator
from datetime import datetime, timezone


class SensorReadingCreate(BaseModel):
    line_id: str = Field(
        ..., min_length=1, max_length=50, description="ID of the manufacturing line"
    )
    sensor_type: str = Field(
        ...,
        min_length=2,
        max_length=50,
        description="Type: fill_level, torque, conveyor_speed",
    )
    value: float = Field(..., description="Raw value of the sensor reading")
    timestamp: datetime = Field(
        ..., description="UTC timestamp generated by the sensor reading"
    )

    # make the model immutable
    model_config = ConfigDict(frozen=True)

    @field_validator("timestamp", mode="before")
    @classmethod
    def ensure_utc_timezone(cls, value):
        """
        Ensures naive incoming CSV strings are interpreted strictly as UTC,
        preventing timezone drift inside PostgreSQL.
        """
        if isinstance(value, str):
            # Parse the string into a datetime object
            dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
            if dt.tzinfo is None:
                return dt.replace(tzinfo=timezone.utc)
            return dt
        if isinstance(value, datetime) and value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value
